### ISSUE TITLE
BACK FIT TOO TIGHT?

### ISSUE THREAD

**Issue by heyitzjesse** [itsjonlebron/Backbone-One-iPad-Mini-Upgrade#2] opened 2024-01-25 16:17 UTC
Hello there,

Thank you so much for making this mod. Its perfect ( specifically the detailed HIGH-RES pictures. But I have a question for you.

Does this look right? it feels like I have to stretch it almost too much ( where it looks like its gonna break and it shows like its bent on the back. Can you please share some pictures from the back? I have attached some pictures to show you. Did I install something wrong? I feel like the slider brackets could be extended a little bit so its more wider then needed but you can push it back and let the tension hold the ipad flush. ( ipad min 6 + backbone gen 2 usb-c).
![5](https://github.com/jonochocki/Backbone-One-iPad-Mini-Upgrade/assets/28378156/49a7520f-adfe-4eae-9ad7-0e1f1336c77c)

![1](https://github.com/jonochocki/Backbone-One-iPad-Mini-Upgrade/assets/28378156/edcd4844-a2e2-487f-bfc0-b0908764762b)
![2](https://github.com/jonochocki/Backbone-One-iPad-Mini-Upgrade/assets/28378156/3958e665-6a34-4c72-af60-f470d6df1028)
![3](https://github.com/jonochocki/Backbone-One-iPad-Mini-Upgrade/assets/28378156/998193cf-448b-4089-b505-cc8c29e5898b)
![4](https://github.com/jonochocki/Backbone-One-iPad-Mini-Upgrade/assets/28378156/f6a115be-aa3d-4aae-9e64-d072e2dc8494)

**Comment by heyitzjesse** [comment] 2024-01-25 16:18
ps, I did try with the "rubber inserts on the side removed on both side but still same issue ( its little better but same issue). I dont know maybe you can make the tracks slightly longer and I can try it? Making or editing 3d files is not my forte!

**Comment by jonochocki** [comment] 2024-01-25 18:04
Hey, @heyitzjesse! Thanks so much for trying out the mod.

I too have a slight bend in the back frame. This is caused by the rail from step(s) 4/5 not being long enough to support the further extension. Ive tried to mitigate this by using the rubber phone adapters on either side (which helps stability too). Unfortunately, extending the rails further is not possible. This is due to the gear wheel within the rail, extending the gear teeth further would cause a collision with the screw used to mount the springs. Ive attached a few of my images for reference.

![Screenshot 2024-01-25 at 2 04 19 PM](https://github.com/jonochocki/Backbone-One-iPad-Mini-Upgrade/assets/24785922/df6d0a5c-13a1-4fe0-81bb-cf92cb23a30e)
![Screenshot 2024-01-25 at 2 04 06 PM](https://github.com/jonochocki/Backbone-One-iPad-Mini-Upgrade/assets/24785922/73fe4a87-c4c4-4107-a69b-17320b1205c1)
![Screenshot 2024-01-25 at 2 03 57 PM](https://github.com/jonochocki/Backbone-One-iPad-Mini-Upgrade/assets/24785922/1c009ce4-de9a-4320-8076-d9e43367e2dc)
![Screenshot 2024-01-25 at 2 03 50 PM](https://github.com/jonochocki/Backbone-One-iPad-Mini-Upgrade/assets/24785922/43579352-baee-4f5b-ba0a-0a7f045a98d1)
![Screenshot 2024-01-25 at 2 03 36 PM](https://github.com/jonochocki/Backbone-One-iPad-Mini-Upgrade/assets/24785922/51f91c4a-8351-4eed-9923-1ca9c7efe800)

**Comment by heyitzjesse** [comment] 2024-01-25 18:42
Hello there,

So I ended up opening it up again and printing another TOP piece. so I have two top pieces one on top and the other flipped on bottom and now it works perfectly. Snug and easy to take out ipad.

Thank you so much!!

**Comment by jonochocki** [comment] 2024-01-25 19:29
@heyitzjesse — Awesome! Great thinking there. Hopefully, your ribbon cable is comfortable in the extended size.

Thanks for sharing, really appreciate your support. Going to close this "issue" for now, if you need anything else, let me know!

**Closed as completed by jonochocki** 2024-01-25 19:29 UTC
